### ISSUE TITLE
[Feature Request] Predefine CPU and Memory Limits

### ISSUE THREAD

**Issue by kharri1073** [SelfhostedPro/Yacht#108]
I grabbed this feature request via reddit - https://www.reddit.com/r/selfhosted/comments/iycwls/yacht_container_management_ui_alpha_is_here/g6cams8/

> I want to pre-define some different sized containers (CPU, mem limits) that they can pick from and run R, Python or Julia amongst other things, but not let them have full access to making changes to the overall container definition - because they like to break things - or have them remember to put in limits and constraints by typing stuff in launch their own container by hand. The problem with the analytics tools is they typically take CPU total - 1 as the amount of resource they can put their hands on which doesn't work in a multi-user environment.

**Comment by SelfhostedPro** [comment]
Which one of these options seems like the best way to go about this?
CPU:

- cpu_count (int) – Number of usable CPUs (Windows only).
- cpu_percent (int) – Usable percentage of the available CPUs (Windows only).
- cpu_period (int) – The length of a CPU period in microseconds.
- cpu_quota (int) – Microseconds of CPU time that the container can get in a CPU period.
- cpu_rt_period (int) – Limit CPU real-time period in microseconds.
- cpu_rt_runtime (int) – Limit CPU real-time runtime in microseconds.
- cpu_shares (int) – CPU shares (relative weight).
- cpuset_cpus (str) – CPUs in which to allow execution (0-3, 0,1).
- cpuset_mems (str) – Memory nodes (MEMs) in which to allow execution (0-3, 0,1). Only effective on NUMA systems.

Memory only has one option so that's easy. Documentation on these is here:

https://docker-py.readthedocs.io/en/stable/containers.html

**Comment by kharri1073** [comment]
Apologies, I'm not the OP, I just saw the feature request and thought it was a useful feature. I'm just starting out with utilizing docker so I can't help with input.

**Comment by SelfhostedPro** [comment]
No worries! Figured I would ask in-case you had any preference. I'll do some research on the best way to go about this.

**Comment by radiohazard-dev** [comment]
When using docker in the command-line, one uses the `--cpu` flag to provide a quota, but this is absent in docker-py. However, docker/docker-py#1920 seems to suggest that it's actually replaced by `nano_cpus`, except you have to give the quota in `core_count * 10^9`.

**Comment by SelfhostedPro** [comment]
Ah, so I would basically just take the number of CPUs they want and use that for core_count in that equation? @radiohazard-dev

**Comment by radiohazard-dev** [comment]
From what I can read, yes — exactly that.

**Comment by SelfhostedPro** [comment]
Perfect. I'll do some testing to make sure. Will definitely get this in the next release if that's it. Thanks for the info! Super helpful.

**Comment by SelfhostedPro** [comment]
So I've got this most of the way done. If anyone can tell me how to do the opposite of 
`core_count * 10^9` it would be much appreciated. I am very bad at math.

**Comment by radiohazard-dev** [comment]
I think what you're looking for is `core_count = nano_cpus / 10^9`, if you're looking to change `nano_cpu` to a core count.

**Comment by SelfhostedPro** [comment]
Once this is done building it should be ready to test on devel: https://github.com/SelfhostedPro/Yacht/actions/runs/603364666

**Comment by SelfhostedPro** [comment]
Memory limits have been added to the devel version as well. `cpus:` in templates will set the nano_cpus when launching a container. `mem_limit` will set the maximum memory. I may change the names  if there are any recommendations.

**Comment by wickedyoda** [comment]
Features added. [on Feb 26, 2021](https://github.com/SelfhostedPro/Yacht/issues/108#issuecomment-786905509)
