### ISSUE TITLE
[Info Request] Please provide advantage of your app compare to others.

### ISSUE THREAD

**Issue by lessload** [SelfhostedPro/Yacht#462]
Please tell user about advantage to use your app, and compare Advantage/Disadvantage to others app. example compare it to Portainer or CasaOS or etc. 

From i try it more simple than portainer, and menu is more easy to understand, good for newbie.
In Term of design CasaOS is better. link https://www.casaos.io/

**Comment by Lwing** [comment]
From the 5 minutes of googling, on big advantage of this project is it's simple backend API. It seems quite straightforward to build a fleet management system that could consume the API. 
Ps: it seems likely I will do this for an upcoming project of mine. This is exactly what I've been searching for. Thank you all

**Comment by wickedyoda** [comment]
@Lwing you are welcome to take on some of the issues and help contribute to the project. There's a lot that can be done and always welcoming others' talents. 

@lessload 
DIfferences? Well, I have never tried CasaOS, from the looks of the site the idea behind it for a home user is awesome. It appears to be a complete OS dedicated to easily managing Docker and other containers for simple management. 

DIfference between it and Yacht, while CasaOS is a complete OS; Yacht is a container similar to Portainer (https://www.portainer.io/). First of all, neither one is a complete OS, these run inside docker after you have installed the OS of your liking and installed the Docker base. They are not a stand-alone OS, for most of us, we use either Debian or Ubuntu server for the system's OS and then visit Docker.com for installing the docker system. Once installed you can follow the instructions at (https://yacht.sh/docs/Installation/Getting_Started) to set up the data volume, pull the image, and build the container. After that you can access the Yacht container with the host-ip:port, I am breaking this down since I don't know your knowledge level, and others might come behind and read. 

Both Yacht and Portainer; allow you to manage, start, stop and remove other containers. Also, allowing you to use the templates in each to build and deploy other containers. Really that's the easy purpose behind Yacht, while I use it; there are other situations where I also use Portainer alongside. Portainer does allow you to manage multiple hosts within one control panel; while this is a feature of Yacht that's in the works it's still got some time before it becomes stable. 

I hope this helps answer some of your questions, while Github is awesome for what it does. We have the SelfhostPro's Discord where there's some limited live support for Yacht and others come together to help others learn and expand. 

https://discord.gg/JfsebxqKDW

Thanks, and if you have more specific questions you are welcome to post them.

WickedYoda
