### ISSUE TITLE
[Bug Report] Dashboard Metrics not working

### ISSUE THREAD

**Issue by SolomonHD** [SelfhostedPro/Yacht#477]
**Describe the bug**
Dashboard Metrics not working

**To Reproduce**
Create a load on a container, wait a couple of minutes, then examine dashboards for accuracy.

**Expected behavior**
Accurate dashboard metrics

**Screenshots**
![2022-05-07 13_45_49-Yacht](https://user-images.githubusercontent.com/10504925/167265999-4cce9f5f-fab7-4592-b98d-381a442ec27e.png)

**Desktop (please complete the following information):**
Windows 11 21H2--> WSL2 --> Ubuntu 20.04

**Additional context**

CPU is stuck at 0%, Memory usage is updating but is roughly 4x-10x times the actual amount used as measured by docker stats.

**Comment by wickedyoda** [comment]
Try the ARM instructions, we have been working on a few things with WSL2 and Yacht lately.

Notes for ARM devices
If you're on arm and graphs aren't showing up add the following to your cmdline.txt:

`cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1`

**Comment by GBT55** [comment]
> Try the ARM instructions, we have been working on a few things with WSL2 and Yacht lately.
> 
> Notes for ARM devices If you're on arm and graphs aren't showing up add the following to your cmdline.txt:
> 
> `cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1`

I did this but dashboard is still blank

**Comment by wickedyoda** [comment]
@GBT55 This is typically an issue on ARM-based systems. Since your system is WSL2 based its amd64 not ARM, try removing the container and image and then recreating it. With the data volume still there config information should still remain. You can also clear the volume if the problem continues. Sounds like you have a corrupt file somewhere. Let us know and we can continue working on it. 

You are also welcome to join our discord server so we can chat directly.

**Comment by SolomonHD** [comment]
For me on WSL2 after adding the `command: cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1` to my docker compose file the dashboard is blank, I'll look into joining the discord server

**Comment by wickedyoda** [comment]
Update?

**Comment by rafsko1** [comment]
Did you manage get the dashboard working?
