### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Gottarocket** [SelfhostedPro/Yacht#485]
I am not sure if its armv7 specific but when clicking on Settings->Update it shows error  and Update option stays non-responsive.

![image](https://user-images.githubusercontent.com/77688111/173200344-1d995cd8-3034-4a45-8bf5-c2ab07923c89.png)
![image](https://user-images.githubusercontent.com/77688111/173200386-9d402045-6b45-44cb-b76f-329fc8202934.png)

**Comment by Gottarocket** [comment]
Raspberry pi 4
Cant update yacht within yacht

**Comment by Dunkelschunkel** [comment]
Just to confirm this issue with my installation. 
Pi4 docker yacht and portainer
![Screenshot_20220719-180007_Fennec](https://user-images.githubusercontent.com/83595637/179796876-09780678-22cf-407a-a241-9390de2a594d.png)

**Comment by wickedyoda** [comment]
Try pulling yacht:devel instead of yacht:latest. The devel is the current work in progress, the latest is almost a year old. Several things have caused @SelfhostedPro to slow down development but we are jump starting him slowly.

**Comment by Gottarocket** [comment]
Got Version: devel-2021-12-04. Hope that's the  latest one. Also not sure how dockerhub works, but I think latest is selected as default. Many tutorials or your website 'Get started' page doesn't have devel mentioned. So would be better if its mentioned or selected by default for armv7 devices

**Comment by wickedyoda** [comment]
Just use devel with no numbers, latest is used when no tag is specified. In this case yacht:devel is the image:tag

**Comment by Gottarocket** [comment]
Oh appreciate the update. Just a small note on the site would be helpful so others can know. Also out of topic but any cli option on yacht. Updating each container one by one is tiresome.

**Comment by wickedyoda** [comment]
The update feature has been working for most, try it after changing the image.

The devel is the "work in progress" so it doesn't always fit the production stable environment. However in this case I want to see if your issues are resolved after changing the image to devel. 

What do you mean to us to update? The image to pull because general users should pull the latest or no tag; or the status of the project?

There are regular updates and interaction within our discord, you're welcome to join and follow there. As the site is concerned it's a pain making regular updates to it and serves the purpose of documentation/how to only.

**Comment by Gottarocket** [comment]
It doesn't show there is new update so cant click on update and replicate issue but I believe its resolved.
The one I mentioned was off topic. It was about other containers. Wanted to know if there is a cli for yacht or  update  all containers at once on gui

**Comment by wickedyoda** [comment]
The update feature has been working for most, try it after changing the image.

The devel is the "work in progress" so it doesn't always fit the production stable environment. However in this case I want to see if your issues are resolved after changing the image to devel. 

What do you mean to us to update? The image to pull because general users should pull the latest or no tag; or the status of the project?

There are regular updates and interaction within our discord, you're welcome to join and follow there. As the site is concerned it's a pain making regular updates to it and serves the purpose of documentation/how to only.

**Comment by wickedyoda** [comment]
The update feature in yacht spins up a watch dog container which then checks all others for updates to the latest tag. It then downloads them and restarts each with the newest image. This does take a little while, some can be a few mins and other configs can take 30 or more. Lots of it depends on the size of the image and speed of its download, rarely is there something instantly seen. 

Is this what you mean? More can be found on GitHub and the yacht site under updates.

**Comment by wickedyoda** [comment]
Yacht is updated as well, if out of date.

**Comment by Gottarocket** [comment]
The time isn't the issue. But would need option to bulk update. Anyway thanks for your time and updates of the image tag

**Comment by Gottarocket** [comment]
Thanks and hope you can add progress bar so we know its done. A small circle filling up next to container would be appreciated. Also my whoogle instance didn't show green dot next to it but actually had an update 2 versions higher. It used to show before not sure why it didn't show now after trying to check updates multiple time. However clicking on update did the update. So which log should I check to know what went wrong in watchtower or yacht gui to show there is an update

**Comment by kwv** [comment]
Seeing the same `Bad Request: Resource ID was not provided` in red toast.   switched from the :latest tag to the :devel tag and the version switched from v0.0.7-alpha.... to  `devel-2021-12-04--00` but the error "Bad Request" remains.

**Comment by wickedyoda** [comment]
I will check it and get back with you.

**Comment by wickedyoda** [comment]
Show the command you're using that's failing in entirety, the complete command.

**Comment by kwv** [comment]
![IMG_0693](https://user-images.githubusercontent.com/308842/233784823-0bddcff9-1a7d-4174-8559-d94932714776.png)
![IMG_0694](https://user-images.githubusercontent.com/308842/233784825-958912cc-1bea-479a-b223-e740dc2036f4.png)

**Comment by kwv** [comment]
launched via:

```
docker run --restart=unless-stopped -d -p 8000:8000 -v /var/run/docker.sock:/var/run/docker.sock -v yacht:/config selfhostedpro/yacht:devel
```
