### ISSUE TITLE
Internal Server Error: error while creating mount source path 

### ISSUE THREAD

**Issue by benek984** [SelfhostedPro/Yacht#489]
I just installed Yacht on fresh install of Ubuntu 22.04. When trying to deploy from template getting error:

Internal Server Error: error while creating mount source path '/yacht/AppData/Config/Heimdall': mkdir /yacht: read-only file system

**Screenshots**

![Screen Shot 2022-06-23 at 20 04 32](https://user-images.githubusercontent.com/62546477/175377849-bb851c06-c106-4374-9046-27381670faab.png)

accessing from:
 - OS: MacOS
 - Browser Chrome
 - Yacht Version v0.0.7-alpha-2022-06-03--21

**Comment by wickedyoda** [comment]
Did you run them as "sudo mkdir [path]" from the cli to make sure the path exists, depending on the location and permissions you might need to make the dir as root? Either that or you didn't add your user as a member of the docker group.  Return to [the read me](https://github.com/SelfhostedPro/Yacht) and go to the bottom where it has the fix for running under wsl. That's not your case but is a common issue and lots of people miss it.

**Comment by benek984** [comment]
I have created /yacht with sudo in cli. I assigned group docker in permission with read and write but still getting this error.
