### ISSUE TITLE
[Feature Request] Update All Button

### ISSUE THREAD

**Issue by slauzon** [SelfhostedPro/Yacht#522]
**Is your feature request related to a problem? Please describe.**
It's frustrating to step through each app individually to update.

**Describe the solution you'd like**
It would be beneficial to have an "Update All" button that would update each container automatically.

**Describe alternatives you've considered**
Another option would be to allow selecting multiple apps via checkbox to the left of the name with a button update.  Similar to the functionality of executing an action against multiple containers like portainer provides.  I will open a ticket around this functionality as well as I see it being beneficial in addition to the "Update All" functionality.

**Comment by UdittLamba** [comment]
I came here to post about this exactly.  
This would be a very nice feature to have if you have a lot of containers running.  
updating one, then refreshing and then updating another one by one is very taxing.

**Comment by wickedyoda** [comment]
@slauzon @UdittLamba 

There are some issues with how the current update works, currently it spins up a watchdog container, updates and deletes. That's why it takes a few minutes to complete. 

These fixes and more enhancements are in the works and coming. 

If you want to try the most current you can pull the tag :devel instead of the latest.  As there are other issues related to updates, I am going to consolidate them and close the ones which repeat soon. 

I also welcome y'all to join our discord and come chat with us directly. Invites are on our site.
