### ISSUE TITLE
[Bug Report] Missing ports after container edit

### ISSUE THREAD

**Issue by Orholt** [SelfhostedPro/Yacht#562]
**Describe the bug**
After clicking edit my exposed ports in hosted config are missing

**To Reproduce**
1. Go to any created container with exposed ports, for my example it's called 'Valheim'
2. Click STOP
3. Go to Edit
4. Go to network section
5. See missing changes (default setting)

**Expected behavior**
Changes I made for ex. exposing port 2456:2456 should be visible

**Screenshots**
![obraz](https://user-images.githubusercontent.com/42500203/209873099-5df122cb-a9cf-452a-9a21-272d85dd90bf.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10.21
 - Browser Firefox
 - Yacht Version v0.0.7-alpha

**Comment by wickedyoda** [comment]
Testing confirmed, looking into it.

**Comment by buzzra** [comment]
I just installed Yacht for the first time, and have already run into this same problem. It is VERY frustrating. Every time an application needs to be changed, ALL the ports have to be remembered and re-entered in addition to whatever changes you were planning to make. Kind of defeats the purpose of Yacht as a graphical container management app. 
Thanks for an otherwise great app and for looking into this. I will just use docker-compose from the cli for now, but will keep an eye on the resolution of this bug.
