### ISSUE TITLE
[Bug Report] Podman installation instructions from wiki are invalid

### ISSUE THREAD

**Issue by QazCetelic** [SelfhostedPro/Yacht#601]
`podman run -v /var/run/podman/podman.sock:/var/run/docker.sock -v yacht:/config -p 8000:8000 --name -d ghcr.io/selfhostedpro/yacht:latest`

The `--name` flag is set, but no value is provided.

I suggest setting the name to `yacht`.

EDIT: I've also been unable to get it to work using Podman, but surprisingly I have been able to start Yacht connected to the Podman socket with docker.

||Podman host|Docker host|
|-|-|-|
|podman.sock| No  | Yes |
|docker.sock| No | Yes |

**Comment by wickedyoda** [comment]
Thank you, I will update the directions as soon as I can or you're welcome to create a branch and do a pull request yourself.  

Most of us don't run podmon so I was unaware.

Also the most updated docs are at dev.yacht.sh make sure you have the dev in front of the domain.

**Comment by wickedyoda** [comment]
Also, the documentation repo is under selfhosted/yacht-docs

**Comment by QazCetelic** [comment]
@wickedyoda
Should I open a separate issue for the issues with Podman as host?

**Comment by wickedyoda** [comment]
> @wickedyoda Should I open a separate issue for the issues with Podman with the host?

Since documentation is controlled through the repo: https://github.com/SelfhostedPro/Yacht-Docs,, please create an issue there for improper directions; you can also make the changes yourselff and I will approve the pull request. 

If there is an issue directly with Yacht, you can create a new issue here for the problem. The use of podman falls under this repo as well. 

If you pull the latest, you can remove it and pull using the `devel` image. This image is more updated and has some fixed iissues and considered in testing and not pushed to master yet. 

You're also welcome to follow the repo "yacht-API" as it's the new version of yacht that's in beta and still being created. Version 2.0 to say, we don't have a time frame for release but its a work in progress. 

Your also welcome to come and speak with us directly within our discord. https://discord.io/selfhostedpros

**Comment by wickedyoda** [comment]
Our most up-to-date documentation can be found a https://dev.yacht.sh
