### ISSUE TITLE
Templates issue

### ISSUE THREAD

**Issue by trimpo87** [SelfhostedPro/Yacht#71]
After installing yacht through portrainer and just using docker compose, both give me the issue with the template from Selfhosted.
In the Yacht UI itself it gives an error: Unauthorized.

Am I doing something wrong or is there a command I need to use for this?

**Comment by SelfhostedPro** [comment]
Which branch of Yacht are you using? What URL are you using to grab the template from github? Are there any logs you can grab for the Yacht conotainer? (`docker ps` to get the container id, then `docker logs <Container ID here>`)

**Comment by trimpo87** [comment]
> Which branch of Yacht are you using? What URL are you using to grab the template from github? Are there any logs you can grab for the Yacht conotainer? (`docker ps` to get the container id, then `docker logs <Container ID here>`)

By now I have uninstalled everything from docker and docker as well (as I am still setting up the whole environment) And after a clean install of Docker and Yacht the link worked for grabbing the template.

Now I only have problems with the path mappings.
I tried different GUID and GPID's ( a new user and the administrator one) but both give me the error "Folder is not writable by user abc" and I can't see my NAS volumes (volume 1/2/3)

Do you need a log for this too?

**Comment by SelfhostedPro** [comment]
Logs from Portainer or Yacht are what are needed. You'll want to find the PUID/PGID for a user that has write permissions to your directories (`id`) then pass through the following environment variables in order to have correct permissions:
 `PUID=<PUIDNumber>` `PGID=<PGIDNumber>`

I am going to close this as it's related to a permissions issue and not directly to Yacht. Please join our discord for help with issues with other projects:
https://discord.gg/KpKutvC
